path:
  ckpt_path: "./output/ckpt/kss"
  log_path: "./output/log/kss"
  result_path: "./output/result/kss"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 300000
  log_step: 1
  synth_step: 1000 
  val_step: 1000
  save_step: 1000
duration:
  binarization_start_steps: 6000
  binarization_loss_enable_steps: 18000
  binarization_loss_warmup_steps: 10000